spring:
  profiles:
    active: dev

---
info:
  pom.artifactId: $project.artifactId$
  pom.version: $project.version$
#management:
#  security:
#    enabled: false                  # 是否打开系统的安全配置
spring:
  messages:
    basename: i18n/Messages,i18n/Pages
  profiles: dev
server:
  port: 80
     
---

spring:
  messages:
    basename: i18n/Messages,i18n/Pages
  profiles: beta
server:
  port: 8082

---

spring:
  messages:
    basename: i18n/Messages,i18n/Pages
  profiles: release
server:
  port: 8083
  